SET DEFINE OFF;
DELETE FROM environmentmissions_fusrap;

INSERT INTO environmentmissions_fusrap (eroc,engineer_reporting_org_name,usace_district_code,district_mission,fusrap_area_of_responsibility) VALUES ('E1','Baltimore District','CENAB','Environmental','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_cw_districts/FeatureServer/0/query?outFields=*&where=SYMBOL%3D%27NAB%27&f=geojson');
INSERT INTO environmentmissions_fusrap (eroc,engineer_reporting_org_name,usace_district_code,district_mission,fusrap_area_of_responsibility) VALUES ('H5','Buffalo District','CELRB','Environmental','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_cw_districts/FeatureServer/0/query?outFields=*&where=SYMBOL%3D%27LRB%27&f=geojson');
INSERT INTO environmentmissions_fusrap (eroc,engineer_reporting_org_name,usace_district_code,district_mission,fusrap_area_of_responsibility) VALUES ('E3','New York District','CENAN','Environmental','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_cw_districts/FeatureServer/0/query?outFields=*&where=SYMBOL%3D%27NAN%27&f=geojson');
INSERT INTO environmentmissions_fusrap (eroc,engineer_reporting_org_name,usace_district_code,district_mission,fusrap_area_of_responsibility) VALUES ('E5','Philadelphia District','CENAP','Environmental','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_cw_districts/FeatureServer/0/query?outFields=*&where=SYMBOL%3D%27NAP%27&f=geojson');
INSERT INTO environmentmissions_fusrap (eroc,engineer_reporting_org_name,usace_district_code,district_mission,fusrap_area_of_responsibility) VALUES ('B3','St. Louis District','CEMVS','Environmental','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_cw_districts/FeatureServer/0/query?outFields=*&where=SYMBOL%3D%27MVS%27&f=geojson');

COMMIT;