SET DEFINE OFF;
DELETE FROM military_regulatorymissions;

INSERT INTO military_regulatorymissions (eroc,engineer_reporting_org_name,usace_district_code,district_mission,military_area_of_resp) VALUES ('J4','Alaska District','CEPOA','Military','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_mil_dist/FeatureServer/0/query?outFields=*&where=DIST%3D%27POA%27&f=geojson');
INSERT INTO military_regulatorymissions (eroc,engineer_reporting_org_name,usace_district_code,district_mission,military_area_of_resp) VALUES ('L4','Albuquerque District','CESPA','Military','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_mil_dist/FeatureServer/0/query?outFields=*&where=DIST%3D%27SPA%27&f=json');
INSERT INTO military_regulatorymissions (eroc,engineer_reporting_org_name,usace_district_code,district_mission,military_area_of_resp) VALUES ('E1','Baltimore District','CENAB','Military','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_mil_dist/FeatureServer/0/query?outFields=*&where=DIST%3D%27NAB%27&f=geojson');
INSERT INTO military_regulatorymissions (eroc,engineer_reporting_org_name,usace_district_code,district_mission,military_area_of_resp) VALUES ('E7','Europe District','CENAU','Military','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_mil_dist/FeatureServer/0/query?outFields=*&where=DIST%3D%27NAU%27&f=geojson');
INSERT INTO military_regulatorymissions (eroc,engineer_reporting_org_name,usace_district_code,district_mission,military_area_of_resp) VALUES ('M2','Fort Worth District','CESWF','Military','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_mil_dist/FeatureServer/0/query?outFields=*&where=DIST%3D%27SWF%27&f=geojson');
INSERT INTO military_regulatorymissions (eroc,engineer_reporting_org_name,usace_district_code,district_mission,military_area_of_resp) VALUES ('J3','Honolulu District','CEPOH','Military','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_mil_dist/FeatureServer/0/query?outFields=*&where=DIST%3D%27POH%27&f=geojson');
INSERT INTO military_regulatorymissions (eroc,engineer_reporting_org_name,usace_district_code,district_mission,military_area_of_resp) VALUES ('J2','Japan District','CEPOJ','Military','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_mil_dist/FeatureServer/0/query?outFields=*&where=DIST%3D%27POJ%27&f=geojson');
INSERT INTO military_regulatorymissions (eroc,engineer_reporting_org_name,usace_district_code,district_mission,military_area_of_resp) VALUES ('G5','Kansas City District','CENWK','Military','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_mil_dist/FeatureServer/0/query?outFields=*&where=DIST%3D%27NWK%27&f=geojson');
INSERT INTO military_regulatorymissions (eroc,engineer_reporting_org_name,usace_district_code,district_mission,military_area_of_resp) VALUES ('J1','Far East District','CEPOF','Military','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_mil_dist/FeatureServer/0/query?outFields=*&where=DIST%3D%27POF%27&f=geojson');
INSERT INTO military_regulatorymissions (eroc,engineer_reporting_org_name,usace_district_code,district_mission,military_area_of_resp) VALUES ('M4','Little Rock District','CESWL','Military','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_mil_dist/FeatureServer/0/query?outFields=*&where=DIST%3D%27SWL%27&f=geojson');
INSERT INTO military_regulatorymissions (eroc,engineer_reporting_org_name,usace_district_code,district_mission,military_area_of_resp) VALUES ('L1','Los Angeles District','CESPL','Military','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_mil_dist/FeatureServer/0/query?outFields=*&where=DIST%3D%27SPL%27&f=geojson');
INSERT INTO military_regulatorymissions (eroc,engineer_reporting_org_name,usace_district_code,district_mission,military_area_of_resp) VALUES ('H2','Louisville District','CELRL','Military','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_mil_dist/FeatureServer/0/query?outFields=*&where=DIST%3D%27LRL%27&f=geojson');
INSERT INTO military_regulatorymissions (eroc,engineer_reporting_org_name,usace_district_code,district_mission,military_area_of_resp) VALUES ('K5','Mobile District','CESAM','Military','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_mil_dist/FeatureServer/0/query?outFields=*&where=DIST%3D%27SAM%27&f=geojson');
INSERT INTO military_regulatorymissions (eroc,engineer_reporting_org_name,usace_district_code,district_mission,military_area_of_resp) VALUES ('E6','New England District','CENAE','Military','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_mil_dist/FeatureServer/0/query?outFields=*&where=DIST%3D%27NAE%27&f=geojson');
INSERT INTO military_regulatorymissions (eroc,engineer_reporting_org_name,usace_district_code,district_mission,military_area_of_resp) VALUES ('E3','New York District','CENAN','Military','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_mil_dist/FeatureServer/0/query?outFields=*&where=DIST%3D%27NAN%27&f=geojson');
INSERT INTO military_regulatorymissions (eroc,engineer_reporting_org_name,usace_district_code,district_mission,military_area_of_resp) VALUES ('E4','Norfolk District','CENAO','Military','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_mil_dist/FeatureServer/0/query?outFields=*&where=DIST%3D%27NAO%27&f=geojson');
INSERT INTO military_regulatorymissions (eroc,engineer_reporting_org_name,usace_district_code,district_mission,military_area_of_resp) VALUES ('G6','Omaha District','CENWO','Military','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_mil_dist/FeatureServer/0/query?outFields=*&where=DIST%3D%27NWO%27&f=geojson');
INSERT INTO military_regulatorymissions (eroc,engineer_reporting_org_name,usace_district_code,district_mission,military_area_of_resp) VALUES ('E5','Philadelphia District','CENAP','Military','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_mil_dist/FeatureServer/0/query?outFields=*&where=DIST%3D%27NAP%27&f=geojson');
INSERT INTO military_regulatorymissions (eroc,engineer_reporting_org_name,usace_district_code,district_mission,military_area_of_resp) VALUES ('L2','Sacramento District','CESPK','Military','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_mil_dist/FeatureServer/0/query?outFields=*&where=DIST%3D%27SPK%27&f=geojson');
INSERT INTO military_regulatorymissions (eroc,engineer_reporting_org_name,usace_district_code,district_mission,military_area_of_resp) VALUES ('K6','Savannah District','CESAS','Military','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_mil_dist/FeatureServer/0/query?outFields=*&where=DIST%3D%27SAS%27&f=geojson');
INSERT INTO military_regulatorymissions (eroc,engineer_reporting_org_name,usace_district_code,district_mission,military_area_of_resp) VALUES ('G3','Seattle District','CENWS','Military','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_mil_dist/FeatureServer/0/query?outFields=*&where=DIST%3D%27NWS%27&f=geojson');
INSERT INTO military_regulatorymissions (eroc,engineer_reporting_org_name,usace_district_code,district_mission,military_area_of_resp) VALUES ('N2','Transatlantic Expeditionary District','CETED','Military','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/usace_mil_dist/FeatureServer/0/query?outFields=*&where=DIST%3D%27TAD%27&f=geojson');

COMMIT;