SET DEFINE OFF;
DELETE FROM districts;

INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('B0','Mississippi Valley Division','B1','Memphis District','CEMVM');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('B0','Mississippi Valley Division','B2','New Orleans District','CEMVN');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('B0','Mississippi Valley Division','B3','St. Louis District','CEMVS');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('B0','Mississippi Valley Division','B4','Vicksburg District','CEMVK');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('B0','Mississippi Valley Division','B5','Rock Island District','CEMVR');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('B0','Mississippi Valley Division','B6','St. Paul District','CEMVP');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('E0','North Atlantic Division','E1','Baltimore District','CENAB');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('E0','North Atlantic Division','E2','Washington Aqueduct','CEWAD');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('E0','North Atlantic Division','E3','New York District','CENAN');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('E0','North Atlantic Division','E4','Norfolk District','CENAO');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('E0','North Atlantic Division','E5','Philadelphia District','CENAP');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('E0','North Atlantic Division','E6','New England District','CENAE');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('E0','North Atlantic Division','E7','Europe District','CENAU');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('G0','Northwestern Division','G2','Portland District','CENWP');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('G0','Northwestern Division','G3','Seattle District','CENWS');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('G0','Northwestern Division','G4','Walla Walla District','CENWW');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('G0','Northwestern Division','G5','Kansas City District','CENWK');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('G0','Northwestern Division','G6','Omaha District','CENWO');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('H0','Great Lakes and Ohio River Division','H1','Huntington District','CELRH');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('H0','Great Lakes and Ohio River Division','H2','Louisville District','CELRL');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('H0','Great Lakes and Ohio River Division','H3','Nashville District','CELRN');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('H0','Great Lakes and Ohio River Division','H4','Pittsburgh District','CELRP');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('H0','Great Lakes and Ohio River Division','H5','Buffalo District','CELRB');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('H0','Great Lakes and Ohio River Division','H6','Chicago District','CELRC');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('H0','Great Lakes and Ohio River Division','H7','Detroit District','CELRE');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('J0','Pacific Ocean Division','J1','Far East District','CEPOF');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('J0','Pacific Ocean Division','J2','Japan District','CEPOJ');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('J0','Pacific Ocean Division','J3','Honolulu District','CEPOH');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('J0','Pacific Ocean Division','J4','Alaska District','CEPOA');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('K0','South Atlantic Division','K2','Charleston District','CESAC');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('K0','South Atlantic Division','K3','Jacksonville District','CESAJ');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('K0','South Atlantic Division','K5','Mobile District','CESAM');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('K0','South Atlantic Division','K6','Savannah District','CESAS');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('K0','South Atlantic Division','K7','Wilmington District','CESAW');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('L0','South Pacific Division','L1','Los Angeles District','CESPL');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('L0','South Pacific Division','L2','Sacramento District','CESPK');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('L0','South Pacific Division','L3','San Francisco District','CESPN');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('L0','South Pacific Division','L4','Albuquerque District','CESPA');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('M0','Southwestern Division','M2','Fort Worth District','CESWF');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('M0','Southwestern Division','M3','Galveston District','CESWG');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('M0','Southwestern Division','M4','Little Rock District','CESWL');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('M0','Southwestern Division','M5','Tulsa District','CESWT');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('N0','Trans Atlantic Division','N2','Transatlantic Expeditionary District','CETED');
INSERT INTO districts (div_eroc,division,eroc,district,usace_district_code) VALUES ('N0','Trans Atlantic Division','P0','Gulf Region District','CEGRD');

COMMIT;