DELETE FROM environmentmissions_fuds;

INSERT INTO environmentmissions_fuds (eroc,engineer_reporting_org_name,usace_district_code,district_mission,fuds_area_of_responsibility) VALUES ('E1','Baltimore District','CENAB','Environmental','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/fuds/FeatureServer/9/query?outFields=*&where=DIST%3D%27NAB%27&f=geojson');
INSERT INTO environmentmissions_fuds (eroc,engineer_reporting_org_name,usace_district_code,district_mission,fuds_area_of_responsibility) VALUES ('E6','New England District','CENAE','Environmental','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/fuds/FeatureServer/9/query?outFields=*&where=DIST%3D%27NAE%27&f=geojson');
INSERT INTO environmentmissions_fuds (eroc,engineer_reporting_org_name,usace_district_code,district_mission,fuds_area_of_responsibility) VALUES ('G5','Kansas City District','CENWK','Environmental','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/fuds/FeatureServer/9/query?outFields=*&where=DIST%3D%27NWK%27&f=geojson');
INSERT INTO environmentmissions_fuds (eroc,engineer_reporting_org_name,usace_district_code,district_mission,fuds_area_of_responsibility) VALUES ('G6','Omaha District','CENWO','Environmental','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/fuds/FeatureServer/9/query?outFields=*&where=DIST%3D%27NWO%27&f=geojson');
INSERT INTO environmentmissions_fuds (eroc,engineer_reporting_org_name,usace_district_code,district_mission,fuds_area_of_responsibility) VALUES ('H2','Louisville District','CELRL','Environmental','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/fuds/FeatureServer/9/query?outFields=*&where=DIST%3D%27LRL%27&f=geojson');
INSERT INTO environmentmissions_fuds (eroc,engineer_reporting_org_name,usace_district_code,district_mission,fuds_area_of_responsibility) VALUES ('K3','Jacksonville District','CESAJ','Environmental','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/fuds/FeatureServer/9/query?outFields=*&where=DIST%3D%27SAJ%27&f=geojson');
INSERT INTO environmentmissions_fuds (eroc,engineer_reporting_org_name,usace_district_code,district_mission,fuds_area_of_responsibility) VALUES ('K6','Savannah District','CESAS','Environmental','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/fuds/FeatureServer/9/query?outFields=*&where=DIST%3D%27SAS%27&f=geojson');
INSERT INTO environmentmissions_fuds (eroc,engineer_reporting_org_name,usace_district_code,district_mission,fuds_area_of_responsibility) VALUES ('L1','Los Angeles District','CESPL','Environmental','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/fuds/FeatureServer/9/query?outFields=*&where=DIST%3D%27SPL%27&f=geojson');
INSERT INTO environmentmissions_fuds (eroc,engineer_reporting_org_name,usace_district_code,district_mission,fuds_area_of_responsibility) VALUES ('M5','Tulsa District','CESWT','Environmental','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/fuds/FeatureServer/9/query?outFields=*&where=DIST%3D%27SWT%27&f=geojson');
INSERT INTO environmentmissions_fuds (eroc,engineer_reporting_org_name,usace_district_code,district_mission,fuds_area_of_responsibility) VALUES ('M2','Fort Worth District','CESWF','Environmental','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/fuds/FeatureServer/9/query?outFields=*&where=DIST%3D%27SWF%27&f=geojson');
INSERT INTO environmentmissions_fuds (eroc,engineer_reporting_org_name,usace_district_code,district_mission,fuds_area_of_responsibility) VALUES ('J4','Alaska District','CEPOA','Environmental','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/fuds/FeatureServer/9/query?outFields=*&where=DIST%3D%27POA%27&f=geojson');
INSERT INTO environmentmissions_fuds (eroc,engineer_reporting_org_name,usace_district_code,district_mission,fuds_area_of_responsibility) VALUES ('J3','Honolulu District','CEPOH','Environmental','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/fuds/FeatureServer/9/query?outFields=*&where=DIST%3D%27POH%27&f=geojson');
INSERT INTO environmentmissions_fuds (eroc,engineer_reporting_org_name,usace_district_code,district_mission,fuds_area_of_responsibility) VALUES ('L2','Sacramento District','CESPK','Environmental','https://services7.arcgis.com/n1YM8pTrFmm7L4hs/arcgis/rest/services/fuds/FeatureServer/9/query?outFields=*&where=DIST%3D%27SPK%27&f=geojson');

COMMIT;

